mkdir -p model/webspam/{1..10}/positive
mkdir -p model/webspam/{1..10}/negative
mkdir -p stats/accuracyPerDataSet/webspam/{1..10}/positive
mkdir -p stats/accuracyPerDataSet/webspam/{1..10}/negative
mkdir -p stats/predictionResults/webspam/{1..10}/positive
mkdir -p stats/predictionResults/webspam/{1..10}/negative
mkdir -p stats/SDMMTestAccuracies/webspam/{1..10}/positive
mkdir -p stats/SDMMTestAccuracies/webspam/{1..10}/negative
mkdir -p stats/weightedmodels/webspam/{1..10}/positive
mkdir -p stats/weightedmodels/webspam/{1..10}/negative
